apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: email-service-service
  name: email-service-service
spec:
  ports:
    - name: "emailservice-port"
      port: 7000
      targetPort: 80
  type: LoadBalancer
  selector:
    io.kompose.service: email-service-service
