# a very minimal declarative config file
_format_version: "2.1"
_transform: true

services:
- connect_timeout: 60000
  host: host.docker.internal
  name: ProductsService
  path: /api/Products
  port: 7200
  protocol: http
  read_timeout: 60000
  retries: 5
  write_timeout: 60000
  routes:
  - name: ProductsService
    methods:
      - GET
      - POST
      - DELETE
      - PUT
    paths:
     - /products
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
