apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: order-service-service
  name: order-service-service
spec:
  ports:
    - name: "orderservice-port"
      port: 8000
      targetPort: 80
  type: LoadBalancer
  selector:
    io.kompose.service: order-service-service
