apiVersion: apps/v1
kind: Deployment
metadata:
  # annotations:
  #   kompose.cmd: kompose convert
  #   kompose.version: 1.26.1 (a9d05d509)
  #   traefik.enable: "true"
  #   traefik.http.middlewares.order-auth.forwardauth.address: http://host.docker.internal:6200/auth
  #   traefik.http.middlewares.order-auth.forwardauth.authResponseHeaders: Email, UserId, UserName, jobTitle
  #   traefik.http.routers.order-service.entrypoints: web
  #   traefik.http.routers.order-service.middlewares: order-auth@docker
  #   traefik.http.routers.order-service.rule: Host(`localhost`) && Path(`/api/orders{any:.*}`)
  #   traefik.port: "80"
  # creationTimestamp: null
  labels:
    io.kompose.service: order-service
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: order-service
  strategy: {}
  template:
    metadata:
      # annotations:
      #   kompose.cmd: kompose convert
      #   kompose.version: 1.26.1 (a9d05d509)
      #   traefik.enable: "true"
      #   traefik.http.middlewares.order-auth.forwardauth.address: http://host.docker.internal:6200/auth
      #   traefik.http.middlewares.order-auth.forwardauth.authResponseHeaders: Email, UserId, UserName, jobTitle
      #   traefik.http.routers.order-service.entrypoints: web
      #   traefik.http.routers.order-service.middlewares: order-auth@docker
      #   traefik.http.routers.order-service.rule: Host(`localhost`) && Path(`/api/orders{any:.*}`)
      #   traefik.port: "80"
      # creationTimestamp: null
      labels:
        # io.kompose.network/basket-net: "true"
        # io.kompose.network/rabbitMQnet: "true"
        # io.kompose.network/traefik-net: "true"
        io.kompose.service: order-service
    spec:
      containers:
        - image: mswsregistry.azurecr.io/order-service:latest
          name: order-service
          resources: {}
      restartPolicy: Always
