apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ default "staging" .Release.Namespace }}
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
     labels:
        app: {{ .Values.name }}
    spec:
      containers:
        - name: {{ .Values.name }}
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: 'root'
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: basketDB
          image: {{ .Values.deployment.image}}
          ports:
            - containerPort: {{ .Values.deployment.containerPort}}

---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ default "staging" .Release.Namespace }}
  name: {{ .Values.name }}
spec:
  selector:
    app: {{ .Values.name }}
  ports:
    - protocol: TCP
      port: 27017
      targetPort: {{ .Values.deployment.containerPort}}