apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: rabbitmq-service
  name: rabbitmq-service
spec:
  ports:
    - name: "4369"
      port: 4369
      targetPort: 4369
    - name: "5671"
      port: 5671
      targetPort: 5671
    - name: "5672"
      port: 5672
      targetPort: 5672
    - name: "25672"
      port: 25672
      targetPort: 25672
    - name: "15671"
      port: 15671
      targetPort: 15671
    - name: "15672"
      port: 15672
      targetPort: 15672
  selector:
    io.kompose.service: rabbitmq-service
status:
  loadBalancer: {}
