apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: payment-service-service
  name: payment-service-service
spec:
  ports:
    - name: "paymentservice-port"
      port: 8000
      targetPort: 80
  type: LoadBalancer
  selector:
    io.kompose.service: payment-service-service
