apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: mssql-service
  name: mssql
spec:
  ports:
    - name: "2666"
      port: 2666
      targetPort: 1433
  type: LoadBalancer
  selector:
    io.kompose.service: mssql-service
