apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ default "staging" .Release.Namespace }}
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
     labels:
        app: {{ .Values.name }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: {{.Values.deployment.image}}
          ports:
            - containerPort: {{ .Values.deployment.containerPort}}


---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ default "staging" .Release.Namespace }}
  name: {{ .Values.name }}
spec:
  selector:
    app: {{ .Values.name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.deployment.containerPort}}