apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: procut-service-service
  name: procut-service-service
spec:
  ports:
    - name: "procutservice-port"
      port: 8000
      targetPort: 80
  type: LoadBalancer
  selector:
    io.kompose.service: procut-service-service
